#! /bin/sh

bspc config border_width              1
bspc config window_gap                20
bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config focus_follows_pointer     true
#bspc config pointer_follows_focus     true
#bspc config pointer_follows_monitor   true
bspc config auto_cancel               true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config focused_border_color      '#00afaf'
bspc config active_border_color       '#002b36'
bspc config normal_border_color       '#002b36'
bspc config presel_border_color       '#6c71C4'
bspc config urgent_border_color       '#dc322f'

bspc monitor -d I II III IV V VI VII VIII IX X

# Hangouts to floating
#bspc rule -a "crx_knipolnnllmklapflnccelgolnpehhpl" floating=true

sxhkd &
urxvtd -q -f -o
# compton -cCzfb -m .9 --shadow-green .1 --use-ewmh-active-win --backend glx
feh --no-fehbg --bg-fill ~/images/wallpapers/random/summer_lake.jpg
~/.config/bspwm/panel &
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
wmname LG3D
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
syndaemon -t -k -i 2 &
