#! /bin/sh
#
# Example panel for LemonBoy's bar

. ~/.config/bspwm/panel_colors

while read -r line ; do
  case $line in
    S*)
      # clock output
      sys_infos="%{F$COLOR_STATUS_FG}${line#?}"
      ;;
    T*)
      # xtitle output
      title="%{F$COLOR_TITLE}${line#?}"
      ;;
    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          O*)
            # focused occupied desktop
            wm_infos="$wm_infos%{A:bspc desktop -f $name:}%{F$COLOR_FOCUSED} ● %{F-}%{A}"
            ;;
          F*)
            # focused free desktop
            wm_infos="$wm_infos%{A:bspc desktop -f $name:}%{F$COLOR_FOCUSED} ○ %{F-}%{A}"
            ;;
          U*)
            # focused urgent desktop
            wm_infos="$wm_infos%{A:bspc desktop -f $name:}%{F$COLOR_URGENT} ● %{F-}%{A}"
            ;;
          o*)
            # occupied desktop
            wm_infos="$wm_infos%{A:bspc desktop -f $name:}%{F$COLOR_UNFOCUSED} ● %{F-}%{A}"
            ;;
          f*)
            # free desktop
            wm_infos="$wm_infos%{A:bspc desktop -f $name:}%{F$COLOR_UNFOCUSED} ○ %{F-}%{A}"
            ;;
          u*)
            # urgent desktop
            wm_infos="$wm_infos%{A:bspc desktop -f $name:}%{F$COLOR_URGENT} ● %{F-}%{A}"
            ;;
          L*)
            # layout
            layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
            #wm_infos="$wm_infos    %{F$COLOR_LAYOUT}$layout%{F-}"
            ;;
          esac
          shift
        done
        ;;
    esac
    printf "%s\n" "%{l} $title %{c}$wm_infos%{r} $sys_infos  "
    #printf "%s\n" "%{l} $title %{c}%{R}$wm_infos%{R}%{r} $sys_infos  "
  done
